name: demo_fashion
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  hive: ^2.2.3
  path_provider: ^2.1.1
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  like_button: ^2.0.5

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

